#! /bin/sh
gforth -m 1M ~/amrforth/v6/interpret.fs $1 -e cr -e bye
# A file full of commands is executed on the target.
# Begin each line with please for command to reach target,
# otherwise host executes the command.
