set browser "konqueror"
set fgColor "black"
set bgColor "LightGray"
set fgTargetColor "blue"
set cursorColor "blue"
set hlColor "blue"
set default_size 12
set main_height 647
set main_width 600
set main_percent 0.750386398758
set orientation vertical
set mode "C2"
set timing 0
