set browser "konqueror"
set fgColor "black"
set bgColor "LightGray"
set fgTargetColor "blue"
set cursorColor "blue"
set hlColor "blue"
set default_size 12
set main_height 608
set main_width 656
set main_percent 0.5
set orientation vertical
set mode "Host"
set timing 0
